version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: autoblog
      POSTGRES_USER: autobloguser
      POSTGRES_PASSWORD: securepass
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
